{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9225031.jpg' text='' width='600' height='870'} /uploads/allimg/150809/1-150P9225031.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9225033.jpg' text='' width='600' height='870'} /uploads/allimg/150809/1-150P9225033.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9225035.jpg' text='' width='900' height='570'} /uploads/allimg/150809/1-150P9225035.jpg {/dede:img}
