{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9215933.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9215933.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9215935.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9215935.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9215938.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9215938.jpg {/dede:img}
