<li>
          <a href="[field:arcurl/]" title="[field:title/]">
            <img src="[field:litpic/]" alt="[field:shorttitle/]">
          </a>
          <div class="colum-info">
            <h3><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h3>
            {dede:tag sort='new' getall='0'}
              <a href='[field:link/]'>[field:tag /]</a>
            {/dede:tag}
          </div>
          
        </li>