<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150809/1-150P9221107.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/150809/1-150P9221107.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="1100";
$z[2]=Array("img"," /uploads/allimg/150809/1-150P9221109.jpg ",241,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/150809/1-150P9221109.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="1090";

?>