<li>
          <a href="[field:arcurl/]" title="[field:title/]">
            <img src="[field:litpic/]" alt="[field:shorttitle/]">
          </a>
          <div class="colum-info">
            <h3><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h3>
          </div>
          <p>[field:id function="GetTags(@me)"/]</p>
          <p>[field:pubdate function="GetDateMK(@me)"/]</p>
          <p>[field:id function="Getimgnum(@me)"/]</p>
        </li>