<?php
$z[0]=Array("arcurl","",13,28);
$z[0][4]=array();
$z[1]=Array("title","",37,52);
$z[1][4]=array();
$z[2]=Array("litpic","",106,121);
$z[2][4]=array();
$z[3]=Array("litpic","",157,172);
$z[3][4]=array();
$z[4]=Array("id","",231,268);
$z[4][4]=array();
$z[4][4]['function']="Getimgnum(@me)";
$z[5]=Array("arcurl","",287,302);
$z[5][4]=array();
$z[6]=Array("title","",304,319);
$z[6][4]=array();

?>