<li class="list">
          <a href="[field:arcurl/]" title="[field:title/]">
            <img src="[field:litpic/]" alt="[field:shorttitle/]">
          </a>
          <div class="colum-info">
            <div class="colun-date">
              <p><i class="iconfont icon-shijian"></i>更新时间：[field:pubdate function="GetDateMK(@me)"/]</p>
              <p><i class="iconfont icon-dianjiliang"></i>[field:id function="Getimgnum(@me)"/]涨</p>
            </div>
            <h3><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h3>
            <p class="tabs"><span>标签：</span>[field:id function="GetTags(@me)"/]</p>
          </div>
        </li>