
-----------------------------------------------
<m:top name='模块管理' c='6,' display='block'>
    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='百度主动推送' link='baidu.php' rank='plus_百度主动推送' target='main' />
<m:item name="百度结构化数据" link="baidusitemap_main.php" rank="plus_百度结构化数据" target="main" />

</m:top>

<m:top item='7' name='手机静态页生成' display='block'>
  <m:item name='更新设置' link='makehtml_m/makehtml_config.php' rank='10' target='main' />
  <m:item name='更新主页HTML' link='makehtml_m/makehtml_index.php' rank='10' target='main' />
  <m:item name='更新栏目HTML' link='makehtml_m/makehtml_list.php' rank='10' target='main' />
  <m:item name='更新文档HTML' link='makehtml_m/makehtml_archives.php' rank='10' target='main' />
  <m:item name='一键更新手机网站' link='makehtml_m/makehtml_all.php' rank='10' target='main' />
</m:top>

<m:top name='XML地图生成器' c='1,' display='block' rank=''>
  <m:item name='XML生成' link='/xapp/index.php?m=admin&a=make' rank='' target='main' />
  <m:item name='织梦二次开发网' link='http://www.dedevvip.com' rank='' target='_blank' />
</m:top>

<m:top name='百度站内搜索' c='6,' display='block' rank=''>
  <m:item name='站内搜索' link='baidusitemap_main.php' rank='' target='main' />
  <m:item name='搜索框管理' link='baidusitemap_main.php?dopost=searchbox2' rank='' target='main' />
  <m:item name='结果页管理' link='baidusitemap_main.php?dopost=searchpage2' rank='' target='main' />
  <m:item name='获得收入' link='baidusitemap_main.php?dopost=income2' rank='' target='main' />  
  <m:item name='数据报表' link='baidusitemap_main.php?dopost=report2' rank='' target='main' />
</m:top>





-----------------------------------------------
