<?php
$z[0]=Array("global","if(@me==1){@me='class=\"on rec-item\"';}else{@me='class=rec-item';}",4,127);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",166,223);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[1][4]['name']="autoindex";
$z[2]=Array("litpic","",344,359);
$z[2][4]=array();
$z[3]=Array("title","",366,380);
$z[3][4]=array();
$z[4]=Array("title","",471,485);
$z[4][4]=array();
$z[5]=Array("typename","",600,617);
$z[5][4]=array();
$z[6]=Array("click","",693,707);
$z[6][4]=array();

?>