<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",4,132);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",173,230);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[1][4]['name']="autoindex";
$z[2]=Array("litpic","",358,373);
$z[2][4]=array();
$z[3]=Array("title","",380,394);
$z[3][4]=array();
$z[4]=Array("arcurl","",500,515);
$z[4][4]=array();
$z[5]=Array("title","",522,536);
$z[5][4]=array();
$z[6]=Array("typeurl","",622,638);
$z[6][4]=array();
$z[7]=Array("typename","",680,697);
$z[7][4]=array();
$z[8]=Array("click","",772,786);
$z[8][4]=array();

?>