<li>
              <div class="rec-left">
                <img src="[field:litpic/]" alt="[field:title/]">
              </div>
              <div class="rec-right">
                <h3>[field:shorttitle/]</h3>
                <div class="rec-info">
                  <span>[field:typename/]</span>
                  <span>[[field:click/]</span>
                </div>
              </div>
            </li>