{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9223052.jpg' text='' width='900' height='553'} /uploads/allimg/150809/1-150P9223052.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9223055.jpg' text='' width='900' height='552'} /uploads/allimg/150809/1-150P9223055.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9223057.jpg' text='' width='900' height='552'} /uploads/allimg/150809/1-150P9223057.jpg {/dede:img}
