<?php
$z[0]=Array("global","if(@me==1){@me='class=\"on\"';}else{@me='';}",59,158);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("litpic","",279,294);
$z[1][4]=array();
$z[2]=Array("title","",301,315);
$z[2][4]=array();
$z[3]=Array("title","",406,420);
$z[3][4]=array();
$z[4]=Array("typename","",535,552);
$z[4][4]=array();
$z[5]=Array("click","",628,642);
$z[5][4]=array();

?>