<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="840";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="225";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170423/1-1F423113156.jpg ",93,238);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/170423/1-1F423113156.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="860";
$z[1][4]['height']="370";

?>