<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '\r\n    <li>' : '');",6,89);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",99,115);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",134,219);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",231,246);
$z[3][4]=array();
$z[4]=Array("imgwidth","",260,278);
$z[4][4]=array();
$z[5]=Array("alttext","",284,301);
$z[5][4]=array();
$z[6]=Array("linkurl","",476,492);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",494,580);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",588,668);
$z[8][4]=array();
$z[8][4]['runphp']="yes";

?>