{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9222944.jpg' text='' width='900' height='552'} /uploads/allimg/150809/1-150P9222944.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9222945.jpg' text='' width='900' height='553'} /uploads/allimg/150809/1-150P9222945.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9222946.jpg' text='' width='900' height='553'} /uploads/allimg/150809/1-150P9222946.jpg {/dede:img}
