{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224U5.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9224U5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224U7.jpg' text='' width='900' height='593'} /uploads/allimg/150809/1-150P9224U7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224Z0.jpg' text='' width='900' height='591'} /uploads/allimg/150809/1-150P9224Z0.jpg {/dede:img}
