<li>
          <a href="[field:arcurl/]" title="[field:title/]">
            <img src="[field:litpic/]" alt="[field:shorttitle/]">
          </a>
          <div class="colum-info">
            <h3><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h3>
            <p class="tabs">[field:id function="GetTags(@me)"/]</p>
            <div class="colun-date">
              <p>[field:pubdate function="GetDateMK(@me)"/]</p>
              <p>[field:id function="Getimgnum(@me)"/]</p>
            </div>
          </div>
        </li>