<li class="rec-item">
              <span>[field:global runphp='yes' name=autoindex][/field:global]</span>
              <div class="rec-left">
                <img src="[field:litpic/]" alt="[field:title/]">
              </div>
              <div class="rec-right">
                <h3>[field:title/]</h3>
                <div class="rec-info">
                  <span>[field:typename/]</span>
                  <span>[field:click/]</span>
                </div>
              </div>
            </li>