{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224631.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9224631.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224633.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9224633.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224636.jpg' text='' width='900' height='600'} /uploads/allimg/150809/1-150P9224636.jpg {/dede:img}
