<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",4,132);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",160,175);
$z[1][4]=array();
$z[2]=Array("global","",223,280);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[2][4]['name']="autoindex";
$z[3]=Array("litpic","",414,429);
$z[3][4]=array();
$z[4]=Array("title","",436,450);
$z[4][4]=array();
$z[5]=Array("title","",553,567);
$z[5][4]=array();
$z[6]=Array("typeurl","",653,669);
$z[6][4]=array();
$z[7]=Array("typename","",711,728);
$z[7][4]=array();
$z[8]=Array("click","",805,819);
$z[8][4]=array();

?>