<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item1\"';}else{@me='class=rec-item1';}",4,134);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",249,264);
$z[1][4]=array();
$z[2]=Array("title","",271,285);
$z[2][4]=array();
$z[3]=Array("arcurl","",385,400);
$z[3][4]=array();
$z[4]=Array("title","",402,416);
$z[4][4]=array();
$z[5]=Array("typeurl","",498,514);
$z[5][4]=array();
$z[6]=Array("typename","",556,573);
$z[6][4]=array();
$z[7]=Array("click","",646,660);
$z[7][4]=array();

?>