{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9215I0.jpg' text='' width='800' height='1200'} /uploads/allimg/150809/1-150P9215I0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9215I1.jpg' text='' width='800' height='1200'} /uploads/allimg/150809/1-150P9215I1.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9215I1-50.jpg' text='' width='900' height='599'} /uploads/allimg/150809/1-150P9215I1-50.jpg {/dede:img}
