<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/161005/1-161005092227.jpg ",93,241);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/161005/1-161005092227.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="690";
$z[1][4]['height']="1002";
$z[2]=Array("img"," /uploads/allimg/161005/1-161005092227-50.jpg ",243,397);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/161005/1-161005092227-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="690";
$z[2][4]['height']="1002";

?>