<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",4,132);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",247,262);
$z[1][4]=array();
$z[2]=Array("title","",269,283);
$z[2][4]=array();
$z[3]=Array("arcurl","",383,398);
$z[3][4]=array();
$z[4]=Array("title","",400,414);
$z[4][4]=array();
$z[5]=Array("typeurl","",496,512);
$z[5][4]=array();
$z[6]=Array("typename","",554,571);
$z[6][4]=array();
$z[7]=Array("click","",644,658);
$z[7][4]=array();

?>