{dede:pagestyle maxwidth='840' pagepicnum='12' ddmaxwidth='225' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/1805/1-1P520130434.jpg' text='刚沐浴的美女梳洗打扮' width='700' height='1050'} /uploads/1805/1-1P520130434.jpg {/dede:img}
{dede:img ddimg='/uploads/1805/1-1P520130504.jpg' text='洗过澡之后认真读书的美女' width='700' height='1050'} /uploads/1805/1-1P520130504.jpg {/dede:img}
{dede:img ddimg='/uploads/1805/1-1P520130523.jpg' text='清秀美女居家长腿玉足诱惑' width='700' height='1050'} /uploads/1805/1-1P520130523.jpg {/dede:img}
{dede:img ddimg='/uploads/1805/1-1P520130615.jpg' text='眉清目秀的清秀佳人' width='700' height='1050'} /uploads/1805/1-1P520130615.jpg {/dede:img}
{dede:img ddimg='/uploads/1805/1-1P520130G7.jpg' text='看到她就知道什么样的女孩清秀' width='700' height='1050'} /uploads/1805/1-1P520130G7.jpg {/dede:img}
{dede:img ddimg='/uploads/1805/1-1P520130J3.jpg' text='瓜子脸微笑床边特写' width='700' height='1050'} /uploads/1805/1-1P520130J3.jpg {/dede:img}
