
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接' target='main' />
<m:item name='百度主动推送' link='baidu.php' rank='plus_百度主动推送' target='main' />
<m:item name="百度结构化数据" link="baidusitemap_main.php" rank="plus_百度结构化数据" target="main" />

