<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",4,132);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",173,230);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[1][4]['name']="autoindex";
$z[2]=Array("typeurl","",357,373);
$z[2][4]=array();
$z[3]=Array("litpic","",413,428);
$z[3][4]=array();
$z[4]=Array("title","",435,449);
$z[4][4]=array();
$z[5]=Array("arcurl","",581,596);
$z[5][4]=array();
$z[6]=Array("title","",598,612);
$z[6][4]=array();
$z[7]=Array("typeurl","",698,714);
$z[7][4]=array();
$z[8]=Array("typename","",756,773);
$z[8][4]=array();
$z[9]=Array("click","",848,862);
$z[9][4]=array();

?>