<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",4,132);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",171,228);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[1][4]['name']="autoindex";
$z[2]=Array("litpic","",349,364);
$z[2][4]=array();
$z[3]=Array("title","",371,385);
$z[3][4]=array();
$z[4]=Array("title","",476,490);
$z[4][4]=array();
$z[5]=Array("typename","",605,622);
$z[5][4]=array();
$z[6]=Array("click","",698,712);
$z[6][4]=array();

?>