{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224944.jpg' text='' width='600' height='900'} /uploads/allimg/150809/1-150P9224944.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224947.jpg' text='' width='960' height='669'} /uploads/allimg/150809/1-150P9224947.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224948.jpg' text='' width='600' height='900'} /uploads/allimg/150809/1-150P9224948.jpg {/dede:img}
