<?php
$z[0]=Array("arcurl","",9,24);
$z[0][4]=array();
$z[1]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",46,174);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("global","",215,272);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[2][4]['name']="autoindex";
$z[3]=Array("litpic","",400,415);
$z[3][4]=array();
$z[4]=Array("title","",422,436);
$z[4][4]=array();
$z[5]=Array("title","",533,547);
$z[5][4]=array();
$z[6]=Array("typeurl","",672,688);
$z[6][4]=array();
$z[7]=Array("typename","",690,707);
$z[7][4]=array();
$z[8]=Array("click","",783,797);
$z[8][4]=array();

?>