{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224142.jpg' text='' width='900' height='571'} /uploads/allimg/150809/1-150P9224142.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224143.jpg' text='' width='900' height='569'} /uploads/allimg/150809/1-150P9224143.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150809/1-150P9224144.jpg' text='' width='800' height='1160'} /uploads/allimg/150809/1-150P9224144.jpg {/dede:img}
