<?php
$z[0]=Array("global","if(@me==1){@me='class=\"current rec-item\"';}else{@me='class=rec-item';}",4,132);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",171,228);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[1][4]['name']="autoindex";
$z[2]=Array("litpic","",350,365);
$z[2][4]=array();
$z[3]=Array("title","",372,386);
$z[3][4]=array();
$z[4]=Array("title","",477,491);
$z[4][4]=array();
$z[5]=Array("typename","",606,623);
$z[5][4]=array();
$z[6]=Array("click","",699,713);
$z[6][4]=array();

?>