<?php
$z[0]=Array("global","",103,129);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",257,283);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n       ",578,711);
$z[2][4]=array();
$z[2][4]['row']="8";
$z[2][4]['type']="top";
$z[3]=Array("channel","\r\n   <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a>\r\n   ",812,927);
$z[3][4]=array();
$z[3][4]['row']="8";
$z[3][4]['type']="top";
$z[4]=Array("myad","",1130,1165);
$z[4][4]=array();
$z[4][4]['name']="indexLeftBanner";

?>