<?php
$z[0]=Array("global","",86,112);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",165,256);
$z[1][4]=array();
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",292,494);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="5";
$z[2][4]['currentstyle']="<li class='current'><a href='~typelink~' >~typename~</a> </li>";

?>