<?php
$z[0]=Array("global","",268,295);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",325,351);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",449,475);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",526,617);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("global","",627,654);
$z[4][4]=array();
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",679,881);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[5][4]['row']="6";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' >~typename~</a> </li>";

?>