<?php
$z[0]=Array("global","",254,280);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",321,348);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",386,416);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",727,753);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",1499,1536);
$z[4][4]=array();
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("arclist","\r\n    <div class=\"post\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title /]\" />\r\n      <p>[field:title /]</p>\r\n      </a></div>\r\n    ",1640,1919);
$z[5][4]=array();
$z[5][4]['titlelen']="22";
$z[5][4]['row']="16";
$z[5][4]['typeid']="all";
$z[5][4]['flag']="p";
$z[6]=Array("include","",1947,1984);
$z[6][4]=array();
$z[6][4]['filename']="foot_m.htm";

?>