<?php
$z[0]=Array("global","",258,284);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",325,352);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",390,420);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",731,757);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",1503,1540);
$z[4][4]=array();
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("list","\r\n    <div class=\"post\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title /]\" />\r\n      <p>[field:title /]</p>\r\n      </a></div>\r\n    ",1644,1899);
$z[5][4]=array();
$z[5][4]['pagesize']="8";
$z[5][4]['titlelen']="22";
$z[6]=Array("pagelist","",1965,2032);
$z[6][4]=array();
$z[6][4]['listsize']="2";
$z[6][4]['listitem']="index pre pageno next end";
$z[7]=Array("include","",2051,2088);
$z[7][4]=array();
$z[7][4]['filename']="foot_m.htm";

?>