<?php
$z[0]=Array("myad","",193,226);
$z[0][4]=array();
$z[0][4]['name']="innerfooterAD";
$z[1]=Array("myad","",422,455);
$z[1][4]=array();
$z[1][4]['name']="indexfooterAD";
$z[2]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n          ",607,773);
$z[2][4]=array();
$z[2][4]['titlelen']="45";
$z[2][4]['row']="8";
$z[2][4]['typeid']="all";
$z[3]=Array("myad","",968,1005);
$z[3][4]=array();
$z[3][4]['name']="indexRightLitpic2";
$z[4]=Array("myad","",1176,1213);
$z[4][4]=array();
$z[4][4]['name']="indexRightLitpic1";

?>